<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Prueba PNN')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet('https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile('https://code.jquery.com/ui/1.12.1/jquery-ui.js')
            ->prependFile('https://code.jquery.com/jquery-1.12.4.js')
            ->prependFile('https://www.google.com/recaptcha/api.js')
        ?>
    </head>
    <body>
        <div class="container">
            <?= $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2017 by Abel Oswaldo Moreno Acevedo.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
