<div class="col-md-12">
    
    <form action="pnntest">
    	<div class="col-md-6 label">Fecha:</div>
    	<div class="col-md-6 campo"><input type="date" id="campo-fecha"></div>    
    	
    	<div class="col-md-6 label">Texto:</div>
    	<div class="col-md-6 campo"><textarea id="campo-texto"></textarea></div>    
    	
    	<div class="col-md-6 label">Departamento:</div>
    	<div class="col-md-6 campo"><select><option>A</option></select></div>   
    	 
    	<div class="col-md-6 label">Municipio:</div>
    	<div class="col-md-6 campo"><select><option>A</option></select></div>    
    	
    	<div class="col-md-6 label">Google Captcha:</div>
    	<div class="col-md-6 campo"><input></div>    
    	
    	<div><input type="submit" value="Enviar" class="Enviar"></div>
    </form>
    
</div>
<script>
	$( function() {
		$( "#campo-fecha" ).datepicker({maxDate: new Date(2017, 11, 31) }); /* Fecha maximo 31 de diciembre de 2017 */
		
		$('#campo-texto').keyup(function() {
		    var len = $(this).val().length;
		    if (len > limit) {
		    	$(this).val($(this).val().substring(0,50));  /* Texto maximo 50 caracteres */
		        return false;
		    }
		});
		
		
  	} );
    /*
    jQuery('#dashboardLink').addClass('active');
    jQuery('#dataLink').removeClass('active');
    */
         
</script>