<div class="col-md-12">
    
    <form action="pnntest">
    	<div class="col-md-6 label">Fecha:</div>
    	<div class="col-md-6 campo"><input type="date" id="campo-fecha" readonly="readonly"></div>    
    	
    	<div class="col-md-6 label">Texto:</div>
    	<div class="col-md-6 campo"><textarea id="campo-texto"></textarea></div>    
    	
    	<div class="col-md-6 label">Departamento:</div>
    	<div class="col-md-6 campo"><select id="campo-departamento"></select></div>   
    	 
    	<div class="col-md-6 label">Municipio:</div>
    	<div class="col-md-6 campo"><select id="campo-municipio"></select></div>    
    	
    	<div class="g-recaptcha" data-sitekey="6LfcLhkUAAAAAJ0FPiDmvWrvPeiQXsif2918nGMB"></div> 
    	
    	<div><input type="button" id="formulario-enviar" value="Enviar" class="Enviar"></div>
    </form>
    
</div>
<script>


	var base_url = 'http://pnntest.841210lab.com/';
	
	var pnn = {
		/* Lista de departamentos */
		departamentos: ['A','B','C','D'], 
		/* Lista de municipios por departamento */
		departamento: {
			A: {
				municipios: [1,2]
			},
			B: {
				municipios: [3]
			},
			C: {
				municipios: [4]
			},
			D: {
				municipios: [5,6]
			}
		},

		enviarFormulario: function(data, callback){
			callback = callback || function() {};
	        var serv = base_url + "application/prueba/update-form";
	        $.ajax({
	            url: serv,
	            type: 'GET',
	            async: true,
	            data: data,
	            success: function(data) {
					alert( data );
	            }
	        });
		}	
	};
	

	$( function() {

		/* Fecha maximo 31 de diciembre de 2017 */
		$( "#campo-fecha" ).datepicker({maxDate: new Date(2017, 11, 31) }); 

		/* Texto maximo 50 caracteres */
		$('#campo-texto').keyup(function() {
		    var len = $(this).val().length;
		    if (len > 50) {
		    	$(this).val($(this).val().substring(0,50));  
		        return false;
		    }
		});

		/* Carga lista de departamentos */
		ldepartamentos = '<option value=0>Seleccione...</option>';
		$.each( pnn.departamentos, function( key, value ) {
			ldepartamentos += '<option value="'+value+'">'+value+'</option>';
		});
		$( '#campo-departamento' ).html(ldepartamentos);

		/* Carga lista de municipios */
		$( '#campo-departamento' ).change( function(){
			departamento = $( '#campo-departamento' ).val();
			lmunicipios = '';
			$.each( pnn.departamento[departamento].municipios, function( key, value ) {
				lmunicipios += '<option value="'+value+'">'+value+'</option>';
			});
			$( '#campo-municipio' ).html(lmunicipios);
		} );

		/* Envia formulario */
		$( '#campo-departamento' ).click( function() {
			datos = { 
						fecha: $( '#campo-fecha' ).val(),
						texto: $( '#campo-texto' ).val(),
						departamento: $( '#campo-departamento' ).val(),
						municipio: $( '#campo-municipio' ).val()
					};		
			pnn.enviarFormulario(datos);	
		} );
		
  	} );
         
</script>