<div class="col-md-12">
    
    <form action="pnntest">
    	<div class="col-md-6 label">Fecha:</div>
    	<div class="col-md-6 campo"><input type="date" id="campo-fecha"></div>    
    	
    	<div class="col-md-6 label">Texto:</div>
    	<div class="col-md-6 campo"><textarea></textarea></div>    
    	
    	<div class="col-md-6 label">Departamento:</div>
    	<div class="col-md-6 campo"><select><option>A</option></select></div>   
    	 
    	<div class="col-md-6 label">Municipio:</div>
    	<div class="col-md-6 campo"><select><option>A</option></select></div>    
    	
    	<div class="col-md-6 label">Google Captcha:</div>
    	<div class="col-md-6 campo"><input></div>    
    	
    	<div><input type="submit" value="Enviar" class="Enviar"></div>
    </form>
    
</div>
<script>
	$( function() {
		$( "#campo-fecha" ).datepicker({maxDate: new Date(2017, 12, 31) });
  	} );
    /*
    jQuery('#dashboardLink').addClass('active');
    jQuery('#dataLink').removeClass('active');
    */
         
</script>